### ISSUE TITLE
Opt-in for currying utils

### ISSUE THREAD

**Issue by Chudesnov** [TinkoffCreditSystems/utils.js#1]
From README.md:

> Most of the utilities are automatically curried

Auto-currying may be very convenient for those who already get it, but it also may be extremely confusing for newcomers (curried functions and higher-order functions in general are harder to use, let alone debug or build new code using them). We could transpile using a custom babel plugin and cut out `curry()` calls where appropriate (from top-level exports at least) by default, and let people opt-in using a different entry point.

I propose that we either implement the following schema using paths:
```js
import map from '@tinkoff/utils/object/map' // requires all args

import mapR from '@tinkoff/utils/R/object/map' // auto-curried
// or
import mapR from '@tinkoff/utils/object/map/R' // auto-curried
```

or named exports
```js
import default as map, {R as mapR } from '@tinkoff/utils/object/map' // for auto-curried exports
```

**Comment by dmitry-korolev** [comment]
"Autocurrying" means that utilities are curryied on-demand and can be used as "normal" non-curried functions.

**Comment by Chudesnov** [comment]
> can be used as "normal" non-curried functions.
leading to unexpected results (return value type is function? wat?) when invoked with an insufficient number of arguments.

**Comment by dmitry-korolev** [comment]
What is an expected result when invoking a function with an insufficient number of arguments?

**Comment by Chudesnov** [comment]
Setting the rest of them to default (or `undefined` if there's no default). That's already done for some utils, but it takes time to find out where it is and where it isn't.

**Comment by dmitry-korolev** [comment]
Default arguments are no less unexpected IMO.
Why would you call `object/map` without second argument? What would you expect when calling `object/filter` without second argument?
Autocurrying is quite explicit and predictable, especially when you know that every single function in the library is autocurried.

**Comment by Chudesnov** [comment]
> Default arguments are no less unexpected 

There's a large difference though: they are a part of ES spec.

This discussion is moving away from my intended goal of making things simpler and into bikeshedding. Let's close it for now and revive if / when more people feel like it's necessary.
