### ISSUE TITLE
Increase coverage of the clone and sanitize methods

### ISSUE THREAD

**Issue by markelog** [TinkoffCreditSystems/utils.js#26]
Right now clone is [45%](https://coveralls.io/builds/19373314/source?filename=src/clone.js) and sanitize around [65%](https://coveralls.io/builds/19373314/source?filename=src/sanitizejs)

**Comment by osorokotyaga** [comment]
sanitize will be removed in future release https://github.com/TinkoffCreditSystems/utils.js/issues/3
