### ISSUE TITLE
Remove docs from the master branch

### ISSUE THREAD

**Issue by dmitry-korolev** [TinkoffCreditSystems/utils.js#4]
Since docs are generated automatically, shouldn't we store them only in the `gh-pages` branch?

**Comment by dmitry-korolev** [comment]
@Tom910 your opinion?

**Comment by Tom910** [comment]
With a separate branch, it is more difficult to update

**Comment by Tom910** [comment]
In this case, if we use https://www.npmjs.com/package/gh-pages maybe some easy
